fix: #71 Error 1046: No database selected
trustbloc/edge-core pull request #72
Opened 2020-09-15 22:20 UTC by llorllale

fixes #71

The MySQL `USE` statement is good only for the connection in which it is executed. When the connection is recycled or a different connection is used from the pool managed by sql.DB then the queries don't work.

This patch ensures all queries are executed by referencing the fully-qualified name of the table: `<schema>.<table>`.

This change breaks usage of the store's `Query()` method depending on whether the DSN specifies the database name and whether the query string is using the fully qualified table name.

Signed-off-by: George Aristy <george.aristy@securekey.com>

2020-09-15 22:36 UTC, talwinder50 approved these changes

2020-09-16 00:03 UTC, DRK3 requested changes

2020-09-16 00:03 UTC, DRK3 commented on pkg/storage/mysql/mysqlstore.go
> +			if openErr != nil {
Isn't `openErr` always nil at this point?

2020-09-16 12:37 UTC, DRK3 commented on pkg/storage/mysql/mysqlstore.go
> +			if openErr != nil {
Disregard my previous comment :)

2020-09-16 12:38 UTC, DRK3 approved these changes

2020-09-16 12:45 UTC, merged