fix: mysql store: need to guard against special characters in object …
trustbloc/edge-core pull request #74
Opened 2020-09-22 02:06 UTC by talwinder50

…identifiers

closes #73

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

2020-09-22 06:09 UTC, fqutishat approved these changes

2020-09-22 10:22 UTC, llorllale requested changes
Please include the backticks in [`s.tableName`](https://github.com/trustbloc/edge-core/blob/ca3afb357f8ab8f578ecbbb05cb5bfdf52f374a6/pkg/storage/mysql/mysqlstore.go#L190)

2020-09-23 07:56 UTC, talwinder50 commented
> Please include the backticks in [`s.tableName`](https://github.com/trustbloc/edge-core/blob/ca3afb357f8ab8f578ecbbb05cb5bfdf52f374a6/pkg/storage/mysql/mysqlstore.go#L190)

done

2020-09-23 11:32 UTC, llorllale approved these changes

2020-09-29 14:37 UTC, merged